services:
  backend:
    build: .
    container_name: movie-recommend-backend
    ports:
      - "8000:8000"
    volumes:
      - ./db/recommend.db:/app/db/recommend.db
    environment:
      - PYTHONPATH=/app

  frontend:
    build: ./client
    container_name: movie-recommend-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
